### ISSUE TITLE
US 07.02.01 -> As a player, I want an estimate of my ranking for the highest scoring unique QR code.

### ISSUE THREAD

**Issue by RyanLeftLegpopper** [CMPUT301W23T02/Codekamon#21]
* App should show ranking based on highest scoring QR code.

**Comment by RyanLeftLegpopper** [comment]
This does not seem to be implemented yet so i put it back from "Under Review" to "In Progress"

**Comment by Rahulpreet7** [comment]
Yeah maybe that was done by mistake, havnt implemented this yet
