### ISSUE TITLE
Divide the Diagram that depicts a series of distinct states into sections, and convert to .png file

### ISSUE THREAD

**Issue by cruzmart** [CMPUT301W23T02/Codekamon#40]
* Demonstrate how each distinct action (for example, pressing a button) results in a different state.
* Split the states into distinct sections from the "storyboard diagram."
* Convert these distinct sections into a ".png" file.

**Comment by cruzmart** [comment]
![Image](https://user-images.githubusercontent.com/73202106/217968112-0cae089b-7ef7-4c3a-b05e-e6e4d615582c.png)

**Comment by cruzmart** [comment]
So far, here is the sample. Please let me know if this is what you were looking for.

**Comment by Rahulpreet7** [comment]
Yes this looks pretty neat and organized now. Thanks for doing this!
